### ISSUE TITLE
Atom: Installation (Mac) - path corrections

### ISSUE THREAD

**Issue by DarrellDenlinger** [AtomicScala/atomic-scala-corrections#15]
Unzipping does not produce a folder literally called “AtomicScala”, and there is no subdirectory called “code”. As it comes out of the zip the paths turn out to be “<unzipdir>/atomic-scala-examples-master/examples”.

testall.sh ends up with permissions 644 after unzipping. So as directed “./testall.sh” will give permission denied. Need to chmod it. I think this is mentioned in the linux section, but mac section needs it too.

**Comment by BruceEckel** [comment]
First issue taken care of via rewritten prose in upcoming 2nd edition.

Added chmod command as per your second issue. Thanks!
