### ISSUE TITLE
'new' keyword

### ISSUE THREAD

**Issue by DarrellDenlinger** [AtomicScala/atomic-scala-corrections#16]
There is an uneasy tension with the ‘new’ keyword. Right up through Summary 2 we are told that everything is an object and instances are created with the ‘new’ keyword. And then we create Vector without the ‘new’ keyword.

The Vectors atom is probably the earliest use of this technique. But it does not really explain why we seem not to follow the "rules" when constructing a Vector.

I know companion objects will be explained later in the book, but it deserves a bit of explanation when the reader first sees it.

**Comment by BruceEckel** [comment]
Added an explanatory paragraph after the first example in "Vectors." Thanks for pointing that out!
