### ISSUE TITLE
Atom: "Handling Non-Values with Option"  Exercise 3 solution is empty

### ISSUE THREAD

**Issue by andrewharmellaw** [AtomicScala/atomic-scala-corrections#18]
Atom: "Handling Non-Values with Option"

Exercise 3 solution is empty.

Suggest something like this is used:

// TicTacToe.scala
class Cell {
  var entry = ' '
  def set(e:Char):Option[String] = {
    if(entry==' ' && (e=='X' || e=='O')) {
      entry = e
      Some("successful move")
    } else
      None
    }
  }

class Grid {
  val cells = Vector(
    Vector(new Cell, new Cell, new Cell),
    Vector(new Cell, new Cell, new Cell),
    Vector(new Cell, new Cell, new Cell)
  )
  def play(e:Char, x:Int, y:Int):Option[String] = {
    if(x < 0 || x > 2 || y < 0 || y > 2)
      None
    else
      cells(x)(y).set(e)
    }
  }

val grid = new Grid
grid.play('X', 1, 1) is Some("successful move")
grid.play('X', 1, 1) is None
grid.play('O', 1, 3) is None

**Comment by BruceEckel** [comment]
Fixed in 2nd edition. Thanks!
