### ISSUE TITLE
Exercise 4 on page 159 requires technique not yet taught

### ISSUE THREAD

**Issue by Speusippus** [AtomicScala/atomic-scala-corrections#24]
The solution given for exercise 4 involves using a class as a type. (The class being used as a type is SimpleTime.)

As far as I can tell, this concept had not been introduced before this exercise. I finally peeked at the solution, saw the first ":SimpleTime" that appears in the code and lightbulbled (oh! You can use classes as types?!) and figured it out.

But I don't think the authors probably meant for the learning to take place that way. Probably when they wrote this exercise they were thinking the use of classes as types had already been introduced, and that would certainly be better from a teaching standpoint--solutions to exercise should generally use already-introduced techniques, or else the student might become over-frustrated.

**Comment by BruceEckel** [comment]
Exercise has been removed for the upcoming 2nd edition. Thanks for the report!
