### ISSUE TITLE
Solution 3 to Comprehensions Exercise 3 problem

### ISSUE THREAD

**Issue by larssn** [AtomicScala/atomic-scala-corrections#26]
This solution doesn't match what the exercise asks (apparently).
We're asked: "Modify yielding3 so the result is defined with an explicit type declaration."

This is yielding3:
def yielding3(v:Vector[Int]):Vector[Int]={
  for {
    n <- v
    if n < 10
    isOdd = (n % 2 != 0)
    if(isOdd)
  } yield {
    val u = n * 10
    u + 2
  }
}

The solution starts using Lists and its generally unclear what the exercise whats me to do.
Here is the solution:
// Solution-3.scala
// Solution to Exercise 3 in "Comprehensions"
import com.atomicscala.AtomicTest._

def yielding3(l: List[Int]) : List[Int] = {
  val result = for { n <- l
    if n < 10
    if n % 2 != 0
  }
  yield n
  result
}
val theList2 = List(1,2,3,5,6,7,8,10,13,14,17)
yielding3(theList2) is Vector(1,3,5,7)

**Comment by BruceEckel** [comment]
Yes, that was messed up, as were the solutions to 2 and 4. Thanks for the report. Fixed in the upcoming 2nd edition.
