### ISSUE TITLE
new Fairy with Fighting symbol name not $anon$1

### ISSUE THREAD

**Issue by njacobs5074** [AtomicScala/atomic-scala-corrections#29]
In the chapter _Polymorphism_, the supplied sample code proscribes the following behavior on line 60 of the sample code:
```
battle(new Fairy with Fighting) is "1, Fight!" // Name: $anon$1
```
However under **Scala code runner version 2.11.5 -- Copyright 2002-2013, LAMP/EPFL**, the string returned by `currentMirror.reflect(o).symbol.toString` when invoked by `Name.className` is simply `$anon` and thus this code fails.

I confirmed that this behavior happens both when running the **scala** command interactively and when running it from within IntelliJ.

The following snippet duplicates the issue:
```
scala> import reflect.runtime.currentMirror
import reflect.runtime.currentMirror
scala> trait Traitorous
defined trait Traitorous
scala> val o1 = new Object with Traitorous
o1: Traitorous = $anon$1@3ecc4651
scala> val o2 = new Object with Traitorous
o2: Traitorous = $anon$1@7c77f8a9
scala> currentMirror.reflect(o1).symbol
res60: reflect.runtime.universe.ClassSymbol = $anon
scala> currentMirror.reflect(o2).symbol
res61: reflect.runtime.universe.ClassSymbol = $anon
````

**Comment by BruceEckel** [comment]
Thanks; I think this happened because of a small change in Scala. I'll be double-checking this before releasing the 2nd edition.

**Comment by BruceEckel** [comment]
It turns out I've already fixed this in the upcoming 2nd edition. Thanks!

**Comment by njacobs5074** [comment]
Awesome!  Thanks for the update.

Nick

On Tue, Feb 17, 2015 at 6:47 PM, Bruce Eckel <notifications@github.com>
wrote:

> It turns out I've already fixed this in the upcoming 2nd edition. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomicScala/atomic-scala-corrections/issues/29#issuecomment-74725722>
> .
>



-- 
Phone: +44 7463 853 913
LinkedIn: http://uk.linkedin.com/in/njacobs5074
Twitter: @njacobs5074

**Comment by waij** [comment]
Using _Scala code runner version 2.12.1_, the output is _anon_.
